# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=40)),
                ('image_caption', models.CharField(max_length=40)),
                ('image_location', models.CharField(max_length=40)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
